USERNAME = "Username"
PASSWORD = "Password"
FIRST_NAME = "First Name"
LAST_NAME = "Last Name"
EMAIL = "Email"
TOKEN_EXPIRED = "Token has expired. Please login again"
SENDING_TIME = "Sending time"
NUMBER_OF_WORDS = "Number of words"
# start.py
START_MESSAGE = "Hello, if you want to change your preferences please send /settings"
LOGIN_OR_REGISTER = "Hi, do you have account or you want to create new one ?"
LOGIN = "Login"
REGISTER = "Register"
# login.py
SEND_USERNAME = "Please reply to this message with your username."
SEND_PASSWORD = "Please reply to this message with your password."
LOGGED_IN = "You have been logged in successfully as {name}."
FIELD_LENGTH = "{} length must be at least {} characters\n{}"
INCORRECT_PASSWORD = f"Incorrect username or password.\n{SEND_USERNAME}"
# register.py
SEND_FIRST_NAME = "Please reply to this message with your first name."
SEND_LAST_NAME = "Please reply to this message with your last name."
SEND_EMAIL = "Please reply to this message with your email."
INVALID_EMAIL = f"Invalid email.\n{SEND_EMAIL}"
SEND_PASSWORD_REGISTER = "Please reply to this message with your password.\n Note: Keep your password in a safe place, your message will be deleted."
USER_ALREADY_EXISTS = "User already exists"
REGISTERED = "You have been registered successfully, you can change your preferences in the settings"
# settings/main.py
SETTINGS_MAIN = "What do you want to change?"
CHANGE_PASSWORD = "Change password"
CHANGE_PREFERENCES = "Change preferences"
# settings/change_password.py
SEND_NEW_PASSWORD = "Please reply to this message with your  new password.\n Note: Keep your password in a safe place, your message will be deleted."
PASSWORD_CHANGED = "Your password has been changed successfully"
# settings/change_preferences/first_name.py
SEND_NEW_FIRST_NAME = "Please reply to this message with your new first name."
FIRST_NAME_CHANGED = "Your first name has been changed successfully"
# settings/change_preferences/first_name.py
SEND_NEW_LAST_NAME = "Please reply to this message with your new last name."
LAST_NAME_CHANGED = "Your last name has been changed successfully"
